### ISSUE TITLE
Core Modules

### ISSUE THREAD

**Issue by jcmlumacad** [TMJPEngineering/generator-tmj#3]
I tried to run this command:

```
yo tmj
```

Source: [link](https://github.com/TMJPEngineering/generator-tmj#both-laravel-and-angular-module)

But the error occurs like this:

![image](https://cloud.githubusercontent.com/assets/21231662/21710366/0d2e5508-d423-11e6-9c04-84494a9a6693.png)

**Comment by rejtg21** [comment]
@jcmlumacad currently all yo tmj commands with creation to laravel is not yet implemented you could create one and ask for pull request. Currently the only supported is angular please see readme for more info.

**Comment by jcmlumacad** [comment]
Oh. I see. Thanks.
